name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "ci"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        qtversion: ['6.6.1']
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_host: windows
            qt_arch: win64_msvc2019_64
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_host: linux
            qt_arch: gcc_64
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            qt_host: linux
            qt_arch: gcc_64
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: ${{ matrix.qtversion }}
        host: '${{ matrix.qt_host }}'
        target: 'desktop'
        arch: '${{ matrix.qt_arch }}'
        dir: '${{github.workspace}}/qt'
        install-deps: 'true'

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
        
    - name: Debug output
      if: always()
      run: |
        tree ./build

    - name: Test on Linux
      if: matrix.os == 'ubuntu-latest'
      run: build/unittests/test_qml_catch2_console
      
    - name: Test on Windows
      if: matrix.os == 'windows-latest'
      run: |
        build/unittests/Release/test_qml_catch2_console.exe
